[package]
name = "simd-benches"
version = "0.5.1-dev"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.uuid-simd]
path = "../uuid-simd"
version = "0.5.1-dev"

[dependencies.hex-simd]
path = "../hex-simd"
version = "0.5.1-dev"

[dependencies.base64-simd]
path = "../base64-simd"
version = "0.5.1-dev"

[dependencies]
getrandom = { version = "0.2", features = ["js"] }
rand = "0.8.4"

[dev-dependencies]
criterion = "0.3.5"
faster-hex = "0.6.1"
uuid = { git = "https://github.com/uuid-rs/uuid", rev = "2d6c147bdfca9612263dd7e82e26155f7ef8bf32" }
base64 = "0.13.0"
radix64 = "0.6.2"

[[bench]]
name = "uuid"
harness = false

[[bench]]
name = "hex"
harness = false

[[bench]]
name = "base64"
harness = false
