[package]
name = "simd-benches"
version = "0.6.3-dev"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
unstable = ["simd-abstraction/unstable"]

[dependencies.simd-abstraction]
path = "../simd-abstraction"
version = "0.7.0"

[dependencies.uuid-simd]
path = "../uuid-simd"
version = "0.7.0"

[dependencies.hex-simd]
path = "../hex-simd"
version = "0.7.0"

[dependencies.base64-simd]
path = "../base64-simd"
version = "0.7.0"

[dependencies]
getrandom = { version = "0.2.7", features = ["js"] }
rand = "0.8.5"
criterion = "0.3.5"
faster-hex = "0.6.1"
uuid = "1.1.2"
base64 = "0.13.0"
radix64 = "0.6.2"

# [[bench]]
# name = "uuid"
# harness = false

[[bench]]
name = "hex"
harness = false

[[bench]]
name = "base64"
harness = false
