on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule: # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule
    - cron: '0 0 * * 0' # at midnight of each sunday


name: CI

jobs:
  stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - run: |
          cargo fmt --all -- --check
      - run: |
          cargo clippy -- -D warnings
      - run: |
          cargo test --release

  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy, miri
      - run: |
          cargo fmt --all -- --check
      - run: |
          cargo clippy -- -D warnings
      - run: |
          cargo test --release --all-features
      - run: |
          cargo miri test --all-features -- --nocapture --test-threads=1
