on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule: # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule
    - cron: '0 0 * * 0' # at midnight of each sunday


name: CI

jobs:
  develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy
      - run: |
          cargo fmt --all -- --check
      - run: |
          cargo clippy -- -D warnings

  rust-version-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
          - 1.63.0 # MSRV
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: |
          cargo build --release --workspace --exclude simd-benches

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testgen:
          - x86_64-unknown-linux-gnu
          - i686-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
          - wasm32-unknown-unknown
          - miri
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with: 
          components: miri
      - uses: extractions/setup-just@v1
      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run: cargo install cross
      - run: |
          T="${{ matrix.testgen }}"
          if [ "$T" = "miri" ]; then
            ./scripts/testgen.py --mode miri | bash -ex
          else
            ./scripts/testgen.py --target $T | bash -ex
          fi
